# Generated by Django 2.1.4 on 2018-12-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='author',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
