# Generated by Django 2.1.4 on 2018-12-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20181214_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='author_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='target_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
