# Generated by Django 2.1.4 on 2018-12-15 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20181214_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='show_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='author',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='target',
            field=models.IntegerField(default=-1),
        ),
    ]
