# Generated by Django 2.1.4 on 2018-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='avatars/'),
        ),
    ]
